### ISSUE TITLE
Unable to run patched rpcdaemon with docker-compose

### ISSUE THREAD

**Issue by META-DREAMER** [wmitsuda/otterscan#155]
Getting this error when trying to setup otterscan with my Erigon node: `[EROR] [01-10|03:03:13.346] Could not connect to DB.  error="incompatible DB Schema versions: reader 3.0.0, database 5.0.0"`

- My Erigon is on v2021.12.03, running it with the given docker-compose file. 
- Used the tag `v2021.12.02-otterscan` from the patched repo.
- Built the patched image using `docker build -t otterscan -f Dockerfile .`
- Updated the docker-compose file to use the newly built otterscan image for rpcdaemon. This is the full compose file:
```yml
version: '2.2'

services:

  erigon:
    image: thorax/erigon:latest
    build: .
    command: erigon --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/tcp"
      - "30304:30304/udp"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.30.2
    user: 1000:1000 # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - "9090:9090"
    volumes:
      - ${ERIGON_PROMETHEUS_CONFIG:-./cmd/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.2.2
    user: 1000:1000 # Uses erigon user from Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ${ERIGON_GRAFANA_CONFIG:-./cmd/prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./cmd/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-grafana:/var/lib/grafana
    restart: unless-stopped

  rpcdaemon:
    image: otterscan:latest
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,erigon,ots,web3,debug,net,trace,txpool --ws
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
    ports:
      - "8545:8545"
    restart: unless-stopped

```
